const ninjas={
  itachi:{name:'宇智波鼬',type:'消耗型',level:'入门',title:'看准分身，留替身反打',threat:'分身压场后接天照，容易被迫交出替身。对手往往会利用你急于近身的心理，把技能节奏连成一条线。',answer:'横向走位等待分身消失，天照前摇出现时再决定替身。近身成功后不要贪连击，先确认对方的反手资源。',timing:'分身消失后的 2 秒',tags:['走位','骗替','反打'],steps:[['观察分身','开局先横移，确认分身的推进方向。'],['保留替身','天照或关键控制命中前，不要因为小伤害交替身。'],['短打撤退','抓到空档后打一套安全伤害，避免被回身反抓。']],avoid:['沿直线持续后退，让分身和天照同时封住路线。','刚看到分身就交位移，暴露下一步落点。','替身后立刻使用长前摇技能。']},
  minato:{name:'波风水门',type:'突进型',level:'进阶',title:'记住标记，别追飞雷神',threat:'多段位移会制造错位，盲目追击很容易被回身起手。真正的压力来自落点不确定，而不是单次位移本身。',answer:'保持中距离，看到苦无落点后向反方向移动。等连续位移结束，再使用范围技能覆盖回身路线。',timing:'连续位移结束时',tags:['封位','中距离','耐心'],steps:[['记落点','苦无出现后先记住位置，不跟着人物视线跑。'],['反向移动','向落点反方向拉开，让回身突进失去最佳角度。'],['范围封位','位移链结束时用范围技能覆盖撤退路线。']],avoid:['追着每次闪现移动，主动进入对方节奏。','在标记附近交出没有保护的长前摇技能。','没有确认落点就使用替身反打。']},
  hashirama:{name:'千手柱间',type:'反手型',level:'高阶',title:'先躲抓取，再抢空档',threat:'大范围木遁限制走位，近身抓取容错很高。靠墙时你的可选路线会迅速减少。',answer:'尽量沿中线拉扯，用短技能试探霸体和抓取。抓取落空出现硬直后，再快速完成起手。',timing:'抓取落空的硬直',tags:['拉扯','抓取','中线'],steps:[['守住中线','不要提前退到墙边，保留左右两侧移动空间。'],['短招试探','使用可快速收招的技能确认霸体与反手。'],['抓空起手','看到抓取落空，立即从侧面进入。']],avoid:['长时间贴墙防守。','霸体状态不明时正面硬换。','抓取落空后仍然犹豫，错过硬直时间。']},
  naruto:{name:'漩涡鸣人',type:'爆发型',level:'入门',title:'防影分身，落地再出手',threat:'影分身起手快，空中追击会扩大连击伤害。起身阶段连续按键很容易再次被抓。',answer:'用 Y 轴移动错开影分身，倒地后先观察对方是否压起身，再决定替身或反手。',timing:'影分身扑空后',tags:['Y轴','起身','替身'],steps:[['斜向走位','不要直线后退，用上下移动让分身扑空。'],['观察压起身','倒地时确认对方是否继续贴近。'],['落地再出手','安全落地后使用短前摇技能抢回节奏。']],avoid:['直线后退到版边。','倒地瞬间连续点击替身和技能。','影分身未结束时正面冲刺。']},
  sasuke:{name:'宇智波佐助',type:'消耗型',level:'进阶',title:'避开火球线，近身施压',threat:'远程火遁与位移组合会持续压低血线。火球封住直线后，位移负责惩罚慌乱走位。',answer:'斜向接近而不是正面冲刺。骗出位移后封住回撤路线，逼对方交出秘卷或替身。',timing:'位移交出后',tags:['斜走','压场','骗技能'],steps:[['避开直线','火球出现时向斜前方移动，缩短距离。'],['骗出位移','用短技能或假动作迫使对方先移动。'],['封住回撤','预判落点，用范围技能压住后路。']],avoid:['站在同一条直线上反复换血。','对方位移仍在时使用全部突进资源。','近身后贪完整连段。']},
  gai:{name:'迈特凯',type:'突进型',level:'入门',title:'不拼先手，等突进落空',threat:'强突进速度快，贴身后容易被持续压制。开局抢技能经常会变成不利换招。',answer:'开局先侧移并保留反手技能。突进越过身位时从侧后方起手，避免正面交换伤害。',timing:'突进越过身位时',tags:['侧移','反手','不换招'],steps:[['开局侧移','先向上下方向移动，观察首个突进。'],['保留反手','不要同时交掉两个技能，至少留下一个保护手段。'],['侧后起手','突进落空越过身位后，从背侧快速起手。']],avoid:['开局站定蓄力或释放长前摇技能。','在正面与突进硬换。','对方突进未交时主动贴近墙边。']}
};
const order=['itachi','minato','hashirama','naruto','sasuke','gai'];
const slug=document.body.dataset.slug,item=ninjas[slug];
if(!item){location.href='../../'}else{
  document.title=`${item.name}对策｜火影忍者手游对策空间`;
  document.querySelector('#app').innerHTML=`<header class="top"><a class="brand" href="../../"><span class="mark">火</span>对策空间</a><a class="back" href="../../#counters">← 返回忍者对策库</a></header><main><section class="hero"><div><div class="eyebrow">NINJA COUNTER / ${item.type}</div><h1>${item.name}</h1><h2>${item.title}</h2></div><aside class="hero-note"><small>最佳反打窗口</small><strong>${item.timing}</strong><div class="tags">${item.tags.map(x=>`<span>#${x}</span>`).join('')}</div></aside></section><section class="grid"><article class="panel"><small>主要威胁</small><h3>先看懂对方要做什么</h3><p>${item.threat}</p></article><article class="panel"><small>核心应对</small><h3>把复杂局面变简单</h3><p>${item.answer}</p></article><article class="panel wide"><small>实战执行</small><h3>三步处理顺序</h3><div class="steps">${item.steps.map((x,i)=>`<div class="step"><b>0${i+1}</b><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}</div></article><article class="panel wide"><small>常见失误</small><h3>这些操作尽量避免</h3><ul class="avoid">${item.avoid.map(x=>`<li>${x}</li>`).join('')}</ul></article></section><nav class="switcher"><a href="../${order[(order.indexOf(slug)+order.length-1)%order.length]}/">← 上一个忍者</a><a href="../${order[(order.indexOf(slug)+1)%order.length]}/">下一个忍者 →</a></nav></main><footer>内容为玩家经验整理，版本更新后请结合实际对局判断。</footer>`;
}
